name = "utils"
license = "MIT"
licenselink = "https://github.com/realorangeone/hugo-theme-utils/blob/master/LICENSE"
homepage = "https://github.com/realorangeone/hugo-theme-utils"

[author]
    name = "Jake Howard"
    homepage = "https://theorangeone.net"
